# Use Python image as base
FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app

COPY requirements.txt /app/requirements.txt
# Copy the backend code into the container
COPY app.py /app

# Install Flask
RUN pip install -r requirements.txt

# Expose the backend port
EXPOSE 5000

# Run the Flask app
CMD ["python", "app.py"]
