# Use the official Elasticsearch image
FROM docker.elastic.co/elasticsearch/elasticsearch:8.5.3

# Set environment variables
ENV discovery.type=single-node
ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"

# Expose the Elasticsearch port
EXPOSE 9200
